const pages = ['Dashboard','IAM Security','EC2 Instances','VPC Designer','Security Center','AWS WAF','CloudWatch','Deployments','Cost Estimator','Reports','Notifications','Settings'];
const icons = ['▦','♙','▣','⌘','◈','⊞','⌁','↗','$','▤','●','⚙'];
const store = JSON.parse(localStorage.getItem('cloudops-demo') || '{"user":"Nora","instances":[{"name":"production-api","type":"t3.large","status":"Running"},{"name":"worker-queue","type":"t3.medium","status":"Running"},{"name":"staging-web","type":"t3.small","status":"Stopped"}]}');
let active = 'Dashboard';
const save = () => localStorage.setItem('cloudops-demo', JSON.stringify(store));

const application = document.createElement('section');
application.id = 'application'; application.className = 'application hidden';
application.innerHTML = `<aside class="app-sidebar"><a class="brand" href="#top"><span class="brand-mark">↯</span><span>CLOUDOPS<br>HUB</span></a><small>WORKSPACE</small><nav class="app-nav">${pages.map((p,i)=>`<button data-page="${p}"><i>${icons[i]}</i>${p}</button>`).join('')}</nav><button class="logout">← Log out</button><div class="built-by">BUILT WITH <b>CODTECH<br>IT SOLUTIONS</b></div></aside><div class="app-content"><header class="app-header"><button class="sidebar-toggle">☰</button><div><small id="crumb">OVERVIEW</small><h2 id="page-title">Dashboard</h2></div><div class="top-tools"><button class="search">⌕ &nbsp; Search <kbd>⌘ K</kbd></button><button class="bell">●<b>3</b></button><button class="theme">◐</button><button class="profile">NR</button></div></header><main id="page-view"></main></div>`;
document.body.append(application);

const metric = (label, value, note, color='') => `<article class="metric ${color}"><small>${label}</small><b>${value}</b><span>${note}</span></article>`;
const chart = () => `<article class="panel chart-panel"><div class="panel-heading"><div><small>LIVE METRICS</small><h3>Infrastructure performance</h3></div><select><option>Last 24 hours</option></select></div><div class="chart-key"><span><i></i>CPU usage</span><span><i></i>Network throughput</span></div><svg viewBox="0 0 800 220" preserveAspectRatio="none"><path class="gridline" d="M0 35H800M0 90H800M0 145H800M0 200H800"/><path class="cpu-line" d="M0 163L50 151L100 167L150 115L200 135L250 82L300 113L350 59L400 100L450 74L500 126L550 87L600 103L650 42L700 70L750 29L800 59"/><path class="network-line" d="M0 185L50 177L100 185L150 157L200 175L250 132L300 153L350 143L400 161L450 113L500 149L550 127L600 138L650 105L700 129L750 95L800 119"/></svg></article>`;
function dashboard(){const running=store.instances.filter(x=>x.status==='Running').length;return `<div class="page-grid"><div class="welcome"><div><span class="live-pill">● ALL SYSTEMS OPERATIONAL</span><h1>Good morning, ${store.user}. <i>Let’s build.</i></h1><p>Here’s what’s happening across your cloud today.</p></div><button class="push-button launch">+ Launch resource</button></div><section class="metric-grid">${metric('SECURITY SCORE','92','↑ 4 points this month','sage')}${metric('RUNNING EC2',running,'Across 2 regions')}${metric('MONTHLY COST','$8,462','↓ 8.6% from last month','yellow')}${metric('ACTIVE DEPLOYS','03','2 healthy · 1 building')}</section><section class="dashboard-split">${chart()}<article class="panel security-card"><small>SECURITY POSTURE</small><div class="score">92<span>/100</span></div><div class="score-bar"><i></i></div><p><b>Strong posture.</b> Two actions will get you to excellent.</p><button class="text-button" data-page="Security Center">Review recommendations →</button></article></section></div>`}
function ec2(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● ${store.instances.length} INSTANCES</span><h1>EC2 Instances</h1><p>Manage compute across every connected AWS account.</p></div><button class="push-button launch">+ Launch instance</button></div><article class="panel table-panel"><table><thead><tr><th>INSTANCE</th><th>TYPE</th><th>REGION</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>${store.instances.map((x,i)=>`<tr><td><b>${x.name}</b><small>i-0a4${i}d89</small></td><td>${x.type}</td><td>ap-south-1</td><td><span class="status ${x.status==='Running'?'on':'off'}">● ${x.status}</span></td><td><button class="table-action" data-instance="${i}">${x.status==='Running'?'Stop':'Start'}</button></td></tr>`).join('')}</tbody></table></article></div>`}
function iam(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● AUDIT COMPLETE</span><h1>IAM Security Audit</h1><p>See and resolve identity risks across your AWS account.</p></div><button class="push-button action">↻ Run new audit</button></div><section class="metric-grid">${metric('SECURITY SCORE','92','↑ 4 points this month','sage')}${metric('IAM USERS','48','43 protected with MFA')}${metric('RISK FINDINGS','05','2 require action','yellow')}${metric('ACCESS KEYS','11','1 unused key found')}</section><article class="panel activity-panel"><div class="panel-heading"><div><small>PRIORITIZED FINDINGS</small><h3>Fix these first</h3></div><button class="text-button">Export CSV ↓</button></div><ul><li><i class="yellow-dot"></i><div><b>3 users do not have MFA enabled</b><span>Medium risk · identity controls</span></div><em>→</em></li><li><i class="yellow-dot"></i><div><b>Access key inactive for over 90 days</b><span>Medium risk · developer-console</span></div><em>→</em></li></ul></article></div>`}
function vpc(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● 3 VPCS DISCOVERED</span><h1>VPC Designer</h1><p>Visualize and plan secure AWS network architecture.</p></div><button class="push-button action">Deploy design →</button></div><article class="panel vpc-canvas"><div class="vpc-toolbar"><button>↖ Select</button><button>＋ VPC</button><button>＋ Subnet</button><button>＋ Gateway</button><span>Drag components to design your network</span></div><div class="network-map"><div class="vpc-box"><b>VPC · production-network</b><small>10.0.0.0/16</small><div class="subnet public"><strong>PUBLIC SUBNET</strong><span>10.0.1.0/24</span><i>◉</i></div><div class="subnet private"><strong>PRIVATE SUBNET</strong><span>10.0.11.0/24</span><i>▣</i></div><div class="gateway">⇄<small>Internet Gateway</small></div></div></div></article><div class="network-summary"><span>✓ 2 subnets</span><span>✓ Internet Gateway</span><span>! No NAT Gateway</span></div></div>`}
function waf(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● WEB ACL ACTIVE</span><h1>Cloud Security — WAF</h1><p>Protect public applications from common exploits and abuse.</p></div><button class="push-button action">Save Web ACL</button></div><section class="metric-grid">${metric('REQUESTS BLOCKED','1,248','Last 24 hours','yellow')}${metric('ALLOWED REQUESTS','38.4k','99.7% legitimate')}${metric('ACTIVE RULES','06','AWS managed + custom','sage')}${metric('THREATS DETECTED','17','No critical threats')}</section><section class="waf-layout"><article class="panel rules"><div class="panel-heading"><div><small>WEB ACL RULES</small><h3>production-api-waf</h3></div></div>${['AWS Core Rule Set','SQL injection protection','Known bad inputs','Rate limiting'].map((x)=>`<label><input type="checkbox" checked> ${x}<span>Active protection rule</span></label>`).join('')}</article><article class="panel attack-analytics"><small>ATTACK ANALYTICS</small><h3>Top blocked categories</h3>${['SQL injection','Bad bots','Rate limit','XSS attempts'].map((x,i)=>`<div class="attack-bar"><span>${x}</span><i style="width:${83-i*19}%"></i><b>${542-i*120}</b></div>`).join('')}</article></section></div>`}
function deployments(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● GITHUB CONNECTED</span><h1>Deployment Center</h1><p>Ship with a clear view of every release.</p></div><button class="push-button action">+ New deployment</button></div><article class="panel pipeline"><small>LATEST RELEASE</small><h3>production-api <span>main</span></h3><div class="pipeline-steps"><div class="done">✓<b>Build</b><small>1m 12s</small></div><div class="done">✓<b>Test</b><small>42s</small></div><div class="current">↗<b>Deploy</b><small>in progress</small></div><div>4<b>Verify</b><small>pending</small></div></div><button class="outline-button">View deployment logs →</button></article></div>`}
function generic(){return `<div class="module"><div class="module-head"><div><span class="live-pill">● CONNECTED</span><h1>${active}</h1><p>Manage and monitor this part of your cloud environment from one place.</p></div><button class="push-button action">Configure →</button></div><section class="metric-grid">${metric('HEALTH STATUS','Healthy','No action required','sage')}${metric('ACTIVE RESOURCES','24','Updated just now')}${metric('LAST SYNC','2 min','AWS sync complete','yellow')}${metric('ALERTS','0','Everything looks good')}</section>${chart()}<article class="panel empty-state"><b>✦</b><h3>Your ${active.toLowerCase()} workspace is ready.</h3><p>Connect more resources to see richer insights here.</p></article></div>`}
function render(){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('selected',b.dataset.page===active));document.querySelector('#page-title').textContent=active;document.querySelector('#crumb').textContent=active==='Dashboard'?'OVERVIEW':`PLATFORM / ${active.toUpperCase()}`;const view=document.querySelector('#page-view');view.innerHTML=active==='Dashboard'?dashboard():active==='IAM Security'?iam():active==='EC2 Instances'?ec2():active==='VPC Designer'?vpc():active==='AWS WAF'?waf():active==='Deployments'?deployments():generic();bindView();}
function toast(message){const x=document.createElement('div');x.className='toast';x.textContent=`✓  ${message}`;document.body.append(x);setTimeout(()=>x.remove(),3000)}
function bindView(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{active=b.dataset.page;render()});document.querySelectorAll('.launch').forEach(b=>b.onclick=launch);document.querySelectorAll('[data-instance]').forEach(b=>b.onclick=()=>{const item=store.instances[Number(b.dataset.instance)];item.status=item.status==='Running'?'Stopped':'Running';save();render()});document.querySelectorAll('.action').forEach(b=>b.onclick=()=>toast('Saved in demo mode. Connect AWS credentials to apply live.'))}
function launch(){const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<form class="modal"><button class="close" type="button">×</button><small>NEW RESOURCE</small><h2>Launch an EC2 instance</h2><label>Instance name<input required placeholder="e.g. payments-api" autofocus></label><label>Instance type<select><option>t3.medium</option><option>t3.large</option></select></label><button class="push-button">Launch instance →</button></form>`;document.body.append(overlay);overlay.querySelector('.close').onclick=()=>overlay.remove();overlay.querySelector('form').onsubmit=e=>{e.preventDefault();store.instances.push({name:e.currentTarget.querySelector('input').value,type:'t3.medium',status:'Running'});save();overlay.remove();active='EC2 Instances';render();toast('Instance is now provisioning.')}}
function openDashboard(){document.querySelector('.site-header').classList.add('hidden');document.querySelector('body > main').classList.add('hidden');document.querySelector('.site-footer').classList.add('hidden');application.classList.remove('hidden');render()}
function login(){const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<form class="modal auth-modal"><span class="brand-mark">↯</span><small>WELCOME TO CLOUDOPS HUB</small><h2>Let’s get you into your cloud.</h2><label>Work email<input type="email" required placeholder="you@company.com" autofocus></label><label>Password<input type="password" required placeholder="••••••••"></label><button class="push-button">Continue to dashboard →</button><p>Demo mode — use any email and password.</p></form>`;document.body.append(overlay);overlay.querySelector('form').onsubmit=e=>{e.preventDefault();store.user=e.currentTarget.querySelector('input').value.split('@')[0]||'Nora';store.user=store.user[0].toUpperCase()+store.user.slice(1);save();overlay.remove();openDashboard()}}
document.querySelectorAll('[data-auth],.login,.price-card .push-button').forEach(b=>b.onclick=e=>{e.preventDefault();login()});
document.querySelector('.logout').onclick=()=>{application.classList.add('hidden');document.querySelector('.site-header').classList.remove('hidden');document.querySelector('body > main').classList.remove('hidden');document.querySelector('.site-footer').classList.remove('hidden')};
document.querySelector('.sidebar-toggle').onclick=()=>application.classList.toggle('sidebar-open');
document.querySelector('.theme').onclick=()=>application.classList.toggle('app-light');
document.querySelector('.bell').onclick=()=>{active='Notifications';render()};
